name: "[Gradle] Determine Build Version"

on:
  workflow_call:
    inputs:
      image:
        description: Which image to run the different tasks on (image must support bash)
        type: string
        required: true
      version_suffix:
        description: The version suffix
        type: string
        required: true
      increment_version:
        description: How to increment the version, or none if no version increment is necessary
        type: string
        required: true
    outputs:
      minecraft_version:
        description: The minecraft version string
        value: ${{ jobs.compute-version.outputs.minecraft_version }}
      current_mod_version:
        description: The current mod version string
        value: ${{ jobs.compute-version.outputs.current_mod_version }}
      current_tag_version:
        description: The current tag version string
        value: ${{ jobs.compute-version.outputs.current_tag_version }}
      current_full_version:
        description: The current full version string
        value: ${{ jobs.compute-version.outputs.current_full_version }}
      next_tag_version:
        description: The next tag version string
        value: ${{ jobs.compute-version.outputs.next_tag_version }}
      next_mod_version:
        description: The next mod version string
        value: ${{ jobs.compute-version.outputs.next_mod_version }}
      next_full_version:
        description: The next full version string
        value: ${{ jobs.compute-version.outputs.next_mod_version }}
      release_name:
        description: The name for the release version
        value: ${{ jobs.compute-version.outputs.release_name }}

permissions:
  contents: read

jobs:
  compute-version:
    runs-on: ${{ inputs.image }}
    outputs:
      minecraft_version: ${{ steps.getMinecraftVersion.outputs.version }}
      current_mod_version: ${{ steps.getModVersion.outputs.version }}
      current_tag_version: v${{ steps.getMinecraftVersion.outputs.version }}-${{ steps.getModVersion.outputs.version }}
      current_full_version: ${{ steps.generateFullVersion.outputs.current_full_version }}
      next_mod_version: ${{ steps.getNextModVersion.outputs.version }}
      next_tag_version: v${{ steps.getMinecraftVersion.outputs.version }}-${{ steps.getNextModVersion.outputs.version }}
      next_full_version: ${{ steps.generateFullVersion.outputs.next_full_version }}
      release_name: ${{ steps.generateReleaseName.outputs.release_name }}
    steps:
      - name: "📦 Checkout"
        uses: actions/checkout@v4

      - name: "📦 Fetch tags" # See https://github.com/actions/checkout/issues/2041
        run: git fetch --tags

      - id: getVersionOrdering
        name: "⚙️ Get version ordering"
        run: |
          uses_mc_version_order_first=$(cat gradle.properties | grep usesMCVersionOrderFirst | cut -d "=" -f 2)
          if [ -z "$uses_mc_version_order_first" ]; then
            uses_mc_version_order_first=false
          fi
          echo "Using MC version order first: $uses_mc_version_order_first"
          echo "uses_mc_version_order_first=$uses_mc_version_order_first" >> "$GITHUB_OUTPUT"

      - id: getMinecraftVersion
        name: "⚙️ Generate Minecraft version"
        run: |
          version=$(cat gradle.properties | grep exactMinecraftVersion | cut -d "=" -f 2)
          echo "Minecraft version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - id: getModVersion
        name: "⚙️ Get mod version"
        run: |
          version=$(git describe --abbrev=0 --tags $(git rev-list --tags=${{ github.ref_name }} --max-count=1) | sed s/v${{ steps.getMinecraftVersion.outputs.version }}-//)
          echo "Current mod version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - id: generateModVersion
        name: "⚙️ Generate next mod version"
        uses: cbrgm/semver-bump-action@v1.0.43
        if: ${{ inputs.increment_version != 'none'}}
        with:
          current-version: ${{ steps.getModVersion.outputs.version }}
          bump-level: ${{ inputs.increment_version }}

      - id: getNextModVersion
        name: "⚙️ Get next mod version"
        run: |
          version=${{ steps.generateModVersion.conclusion != 'skipped' && steps.generateModVersion.outputs.new_version || steps.getModVersion.outputs.version }}
          echo "Next mod version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"
          - id: generateFullVersion

      - id: generateFullVersion
        name: "Generate full version"
        run: |
          if [[ -n "${{inputs.version_suffix}}" ]]
          then
            if [ ${{ steps.getVersionOrdering.outputs.uses_mc_version_order_first }} == "true" ] 
            then
              current_full_version="${{ steps.getMinecraftVersion.outputs.version }}-${{ steps.getModVersion.outputs.version }}-${{ inputs.version_suffix }}"
              next_full_version="${{ steps.getMinecraftVersion.outputs.version }}-${{ steps.getNextModVersion.outputs.version }}-${{ inputs.version_suffix }}"
            else
              current_full_version="${{ steps.getModVersion.outputs.version }}-${{ steps.getMinecraftVersion.outputs.minecraft_version }}-${{ inputs.version_suffix }}"
              next_full_version="${{ steps.getNextModVersion.outputs.version }}-${{ steps.getMinecraftVersion.outputs.minecraft_version }}-${{ inputs.version_suffix }}"
            fi
          else
            if [ ${{ steps.getVersionOrdering.outputs.uses_mc_version_order_first }} == "true" ] 
            then
              current_full_version="${{ steps.getMinecraftVersion.outputs.minecraft_version }}-${{ steps.getModVersion.outputs.version }}"
              next_full_version="${{ steps.getMinecraftVersion.outputs.minecraft_version }}-${{ steps.getNextModVersion.outputs.version }}"
            else
              current_full_version="${{ steps.getModVersion.outputs.version }}-${{ steps.getMinecraftVersion.outputs.minecraft_version }}"
              next_full_version="${{ steps.getNextModVersion.outputs.version }}-${{ steps.getMinecraftVersion.outputs.minecraft_version }}"
            fi
          fi
          echo "Current full version: ${next_full_version}"
          echo "Next full version: ${next_full_version}"
          echo "current_full_version=${current_full_version}" >> "$GITHUB_OUTPUT"
          echo "next_full_version=${next_full_version}" >> "$GITHUB_OUTPUT"

      - id: generateReleaseName
        name: "⚙️ Generate release name"
        run: |
          release_name="Version ${{ steps.getNextModVersion.outputs.version }} for Minecraft ${{ steps.getMinecraftVersion.outputs.version }}"
          echo "Release name: $release_name"
          echo "release_name=$release_name" >> "$GITHUB_OUTPUT"
