name: "[Gradle] Persist Build Version"

on:
  workflow_call:
    inputs:
      image:
        description: Which image to run the different tasks on (image must support bash)
        type: string
        required: true

permissions:
  contents: write

jobs:
  compute-version:
    runs-on: ${{ inputs.image }}
    steps:
      - name: "📦 Checkout"
        uses: actions/checkout@v4
