name: "[Project] Build project & pre-release"

on:
  workflow_call:
    inputs:
      image:
        description: Which image to run the different tasks on (image must support bash)
        type: string
        required: false
        default: ubuntu-latest
      java:
        description: The version of Java to use to run Gradle
        type: string
        required: false
        default: "21"
      version_file:
        description: The file name/path where the version number is stored
        type: string
        required: false
        default: VERSION.txt
      version_suffix:
        description: The suffix to put behind the branch, defaults to the branch name
        type: string
        required: false
        default: ${{ github.ref_name }}
      create_prerelease:
        description: Whether to make a prerelease version or not
        type: boolean
        required: false
        default: false
      gradle_build_task:
        description: The name of the gradle build task to use
        type: string
        required: false
        default: build
      gradle_publish_task:
        description: The name of the gradle publish task to use
        type: string
        required: false
        default: publish
    secrets:
      GRADLE_ENCRYPTION_KEY:
        description: The AES key to enable Gradle cache encryption
        required: false

permissions:
  contents: read

jobs:
  generate-build-information:
    runs-on: ${{ inputs.image }}
    outputs:
      version_suffix: ${{ steps.computeBranchSuffix.outputs.version_suffix }}
    steps:
      - id: computeBranchSuffix
        name: "⚙️ Compute branch suffix"
        run: |
          cleanedSuffix=$(echo ${{ inputs.version_suffix }} | sed 's/[^a-zA-Z0-9]/-/g')
          echo "Cleaned suffix: $cleanedSuffix"
          echo "version_suffix=$cleanedSuffix" >> "$GITHUB_OUTPUT"

  compute-version:
    needs:
      - generate-build-information
    uses: ./.github/workflows/internal.gradle.version.yaml
    with:
      image: ${{ inputs.image }}
      version_file: ${{ inputs.version_file }}
      version_suffix: ${{ needs.generate-build-information.outputs.version_suffix }}-rc
      increment_version: ${{ inputs.create_prerelease && 'prerelease' || 'none' }}
    secrets: inherit

  build:
    needs:
      - compute-version
    uses: ./.github/workflows/internal.gradle.build.yaml
    with:
      image: ${{ inputs.image }}
      java: ${{ inputs.java }}
      gradle_build_task: ${{ inputs.gradle_build_task }}
      version: ${{ needs.compute-version.outputs.next_full_version }}
    secrets: inherit

  pre-release:
    needs:
      - compute-version
    if: ${{ inputs.create_prerelease }}
    uses: ./.github/workflows/internal.gradle.publish.yaml
    with:
      image: ${{ inputs.image }}
      java: ${{ inputs.java }}
      gradle_publish_task: ${{ inputs.gradle_publish_task }}
      version: ${{ needs.compute-version.outputs.next_full_version }}
    secrets: inherit
